"""面向用户的文案（**自动生成，不要手改**）。

生成命令： `python tools/gen_copy_text.py`
唯一事实源： `mindcare/copywriting.md`（点分 ID）+ `mindcare/copywriting.json`
（`OVERRIDES` / `JSON_ONLY` 的条目运行时读 JSON，见生成器头部说明）。

共 453 条。
"""
from __future__ import annotations

from typing import Dict

#: `ID -> 文案`。界面代码只写 ID，不写中文。
TEXT: Dict[str, str] = {
    "c.action.back": "上一步",
    "c.action.cancel": "取消",
    "c.action.close": "关闭",
    "c.action.confirm": "确定",
    "c.action.copied": "已经复制好了，可以先存到别处。",
    "c.action.copy": "复制这段文字",
    "c.action.gotIt": "知道了",
    "c.action.logout": "退出登录",
    "c.action.next": "下一步",
    "c.action.retry": "再试一次",
    "c.action.save": "保存",
    "c.action.skip": "跳过",
    "c.action.submit": "提交",
    "c.disclaimer.nondiagnostic": "这里的内容是关怀用的参考，不构成医学诊断。如果一直觉得不太好，可以让家人或老师陪你去找医生聊聊。",
    "c.empty.detail.shared": "这次没有学生愿意让你看到的内容，可以先用线下的方式关心。",
    "c.empty.detail.unshared": "该生选择暂不分享，可通过线下方式关心",
    "c.empty.feedback.mine": "你还没有提交过学校的反馈。想到了随时可以写。",
    "c.empty.profile.dates": "还没有打过点的日子。今天可以从心情那一题开始。",
    "c.empty.profile.submissions": "这一天你还没有留下记录。想写的时候再来。",
    "c.empty.search": "没有找到对应的同学，换个关键词试试。",
    "c.empty.treehole.list": "这里还空着。想写的时候，随时都可以来。",
    "c.empty.triage.filtered": "这个条件下暂时没有学生。换个条件看看也可以。",
    "c.empty.triage.list": "这里还很安静。有学生写下自己的心情时，会出现在这里。",
    "c.engine.notReady": "数据库正在恢复，稍等一下再试就好。",
    "c.engine.notReady.action": "现在还不能提交，等一会儿再试一次。",
    "c.error.1001": "登录状态过期了，重新登录一下就好。",
    "c.error.1002": "这段内容还没有被分享，所以暂时看不到。",
    "c.error.2001": "有一项还没有填写完整，检查一下再提交就好。",
    "c.error.2001.field": "2001（带字段名） | 这一项还需要补一下：{field}",
    "c.error.2002": "没有找到这段内容，可能已经被移走了。",
    "c.error.3001": "这里出了点小状况，我们已经在看了，再试一次就好。",
    "c.error.4001": "提交得有点快，歇一分钟再试就好。",
    "c.error.network": "网络好像有点慢，等会儿再试就好。",
    "c.error.timeout.retry": "（超时重试） | 刚才没送达，我们替你重试了一次，内容还留着。",
    "c.error.unknown": "未知码 | 这里出了点小状况，再试一次就好。",
    "c.hotline.beijing.name": "北京心理援助热线",
    "c.hotline.beijing.number": "010-82951332",
    "c.hotline.emergency.name": "紧急情况（急救 / 报警）",
    "c.hotline.emergency.number": "120 / 110",
    "c.hotline.footer": "这些电话 24 小时有人接，说\"我现在不太好\"就可以。",
    "c.hotline.line": "全国统一心理援助热线 12356 ｜ 北京心理援助热线 010-82951332 ｜ 紧急情况拨打 120 / 110",
    "c.hotline.national.name": "全国统一心理援助热线",
    "c.hotline.national.number": "12356",
    "c.hotline.title": "如果现在很难受，可以打这些电话",
    "c.loading.generic": "稍等一下…",
    "c.loading.triage": "正在把这些内容取过来…",
    "c.login.action.register": "注册并进入",
    "c.login.action.submit": "登录",
    "c.login.className": "班级",
    "c.login.demoNote": "首次使用请先注册，填写班级、姓名、号次与密码。",
    "c.login.name": "姓名",
    "c.login.password": "密码",
    "c.login.studentNo": "号次",
    "c.login.studentNo.format": "号次是你的编号，注册后用它登录。",
    "c.login.subtitle": "今天的你，还好吗？",
    "c.login.title": "欢迎回来",
    "c.login.toggle.login": "已有账号？去登录",
    "c.login.toggle.register": "没有账号？去注册",
    "c.profile.chart.empty": "这一周还没有情绪记录，先去心情那一题写写看。",
    "c.profile.chart.title": "一周情绪",
    "c.profile.chart.week.next": "下一周",
    "c.profile.chart.week.prev": "上一周",
    "c.profile.view.chart": "情绪可视化",
    "c.profile.view.records": "档案记录",
    "c.schedule.cell.blocked": "不可约",
    "c.schedule.cell.free": "可约",
    "c.schedule.cell.mine": "我的",
    "c.schedule.cell.taken": "已约",
    "c.schedule.col.period": "节次",
    "c.schedule.empty.week": "这一周没有可预约的时间，换一周看看。",
    "c.schedule.legend.blocked": "老师不方便（红框）",
    "c.schedule.legend.free": "可预约",
    "c.schedule.legend.mine": "我约的",
    "c.schedule.legend.past": "已经过去",
    "c.schedule.legend.taken": "已有同学约了",
    "c.schedule.legend.title": "方块说明",
    "c.schedule.monthNav": "月份",
    "c.schedule.period.1": "第1节",
    "c.schedule.period.2": "第2节",
    "c.schedule.period.3": "第3节",
    "c.schedule.period.4": "第4节",
    "c.schedule.period.5": "第5节",
    "c.schedule.period.6": "第6节",
    "c.schedule.period.7": "第7节",
    "c.schedule.period.8": "第8节",
    "c.schedule.week.current": "回到本周",
    "c.schedule.week.next": "下一周",
    "c.schedule.week.prev": "上一周",
    "c.schedule.week.range": "{start} - {end}",
    "c.schedule.weekday.1": "周一",
    "c.schedule.weekday.2": "周二",
    "c.schedule.weekday.3": "周三",
    "c.schedule.weekday.4": "周四",
    "c.schedule.weekday.5": "周五",
    "c.schedule.weekday.6": "周六",
    "c.schedule.weekday.7": "周日",
    "c.schedule.year": "年份",
    "c.tab.about": "关于",
    "c.tab.appointment": "预约",
    "c.tab.profile": "我的档案",
    "c.tab.questionnaire": "问卷",
    "home.activity.appointment": "你预约了心理老师。",
    "home.activity.empty": "还没有活动记录，从今天的心情打卡开始吧。",
    "home.activity.questionnaire": "你完成了今日心情打卡。",
    "home.activity.title": "最近活动",
    "home.activity.treehole": "你写了一篇树洞。",
    "home.card.appointment.desc": "和老师聊一聊，让心情轻一点",
    "home.card.profile.desc": "看看一路走来的自己",
    "home.card.questionnaire.desc": "给今天的情绪做个小小的记录",
    "home.card.treehole.desc": "把心里想说的话悄悄放进来",
    "home.footer.line": "慢慢来，也算在前进。",
    "home.nav.brand": "见山",
    "home.nav.home": "首页",
    "home.nav.settings": "设置",
    "home.nav.slogan": "在这里，遇见更好的自己",
    "home.note.1": "你已经很努力了，不必对自己太苛刻。慢慢来，山会等你。",
    "home.note.2": "今天也辛苦了。休息一下，也是认真生活的一部分。",
    "home.note.3": "不必急着变好，先把今天过成舒服的样子。",
    "home.note.4": "你走过的每一步，都在慢慢把自己带到想去的地方。",
    "home.note.change": "换一条",
    "home.note.sign": "—— 见山",
    "home.note.title": "今日的小纸条",
    "home.welcome.hello": "你好，{name}",
    "home.welcome.subtitle": "今天的你，也在努力发光。",
    "s.appointment.confirm": "确认预约",
    "s.appointment.day": "日期",
    "s.appointment.error.blocked": "老师把这段时间设成了不可预约，换一个吧。",
    "s.appointment.error.none": "先点一个小方块，选好时间再来确认。",
    "s.appointment.error.past": "这个时间已经过去了，选一个还没到的时间。",
    "s.appointment.error.taken": "这个时间已经有同学约了，换一个吧。",
    "s.appointment.hint.grid": "红框是老师这节课不方便的时间，点不了。",
    "s.appointment.month": "月份",
    "s.appointment.profile.class": "班级",
    "s.appointment.profile.name": "姓名",
    "s.appointment.profile.none": "还没有读到你的班级学号，登录后会自动带上。",
    "s.appointment.profile.sid": "学号",
    "s.appointment.profile.title": "预约人信息",
    "s.appointment.selected": "已选：{date} {weekday} 第{period}节 {start}-{end}",
    "s.appointment.selected.none": "还没选时间",
    "s.appointment.share.hint": "不选也没关系，老师只会看到你的班级、学号和预约时间。",
    "s.appointment.share.questionnaire": "我这次的测评内容",
    "s.appointment.share.title": "除了基本信息，还想一起给老师看哪些？（可选）",
    "s.appointment.share.treehole": "我的树洞记录",
    "s.appointment.subtitle": "横着是星期，竖着是第几节课。点一个小方块就选好了。",
    "s.appointment.success": "预约好了，老师会在这个时间看到你。",
    "s.appointment.teacher.empty": "该时段暂无可预约的老师，换一个时间试试",
    "s.appointment.teacher.loading": "正在查询可预约老师…",
    "s.appointment.teacher.none": "不指定老师",
    "s.appointment.teacher.title": "选择预约老师（可选）",
    "s.appointment.time": "时间段",
    "s.appointment.title": "挑一个方便来找老师的时间",
    "s.appointment.year": "年份",
    "s.branch.a.next": "看看接下来 →",
    "s.branch.a.title": "今天挺好的。",
    "s.branch.a.toast.saving": "正在保存…",
    "s.branch.b.hint.skip": "不想写也没关系，跳过一样可以往下走。",
    "s.branch.b.optionalTag": "选填",
    "s.branch.b.placeholder": "可以不填，直接跳过就好。",
    "s.branch.b.question": "如果愿意，可以说说是因为什么。",
    "s.branch.b.skip": "先跳过",
    "s.branch.b.submit": "写好了，继续 →",
    "s.branch.b.title": "今天平平淡淡的，也挺好。",
    "s.branch.c.subtitle": "接下来几句话，可以慢慢选、慢慢写。",
    "s.branch.c.title": "谢谢你愿意说出来。",
    "s.end.happy.action.close": "先这样，再见",
    "s.end.happy.action.treehole": "去树洞写一句",
    "s.end.happy.body": "愿这份轻松多待一会儿。想留个纪念的话，可以去树洞写一句，以后翻到会很暖。",
    "s.end.happy.footer": "明天也欢迎你再来看看自己。",
    "s.end.happy.title": "恭喜你今天有个好心情 🌿",
    "s.end.help.action.close": "知道了",
    "s.end.help.body": "你写的这段内容，心理老师会尽快看到，并且会以让你舒服的方式来找你。现在可以先把这件事放一放。",
    "s.end.help.footer": "如果此刻很难受，随时可以打 12356，有人会接。",
    "s.end.help.title": "已经送到老师那里了。",
    "s.end.plain.action.close": "先这样，再见",
    "s.end.plain.action.treehole": "去树洞写一句",
    "s.end.plain.footer": "如果哪天心里有点沉，随时回来和我说说。",
    "s.end.plain.tips": "可以出去走走，晒到一点光；也可以和朋友随便聊两句，或者把今天记一句在树洞里。不用勉强自己「应该开心」。",
    "s.end.plain.title": "今天平平淡淡的，也很好。",
    "s.end.revoked.action.back": "回到我的档案",
    "s.end.revoked.action.close": "知道了",
    "s.end.revoked.body": "老师那边不会再看到这一段。你写下的内容还留在这里，只是重新回到了你手里。",
    "s.end.revoked.footer": "如果之后又想让老师知道，重新填一次、选「请求帮助」就可以。",
    "s.end.revoked.hotline": "如果此刻很难受，随时可以打 12356，有人会接。",
    "s.end.revoked.reassure": "改主意是你的权利，什么时候都算数。",
    "s.end.revoked.title": "已经改回只有你自己能看到了。",
    "s.end.selfcare.action.close": "先这样，再见",
    "s.end.selfcare.action.treehole": "写树洞",
    "s.end.selfcare.body": "内容已经保存好了，只有你自己能看到。可以试一两件小事，也可以什么都不做，先歇一会儿。",
    "s.end.selfcare.hotline.body": "全国统一心理援助热线 12356 ｜ 北京心理援助热线 010-82951332 ｜ 紧急情况拨打 120 / 110",
    "s.end.selfcare.hotline.title": "如果现在很难受，可以打这些电话",
    "s.end.selfcare.suggest.breath": "慢慢吸气 4 秒，停 7 秒，缓缓呼 8 秒，做 4 轮。",
    "s.end.selfcare.suggest.friend": "找一个让你放松的人待一会儿，哪怕不说话。",
    "s.end.selfcare.suggest.treehole": "心里的话写进树洞，这里只有你自己能看到。",
    "s.end.selfcare.suggest.walk": "站起来走一走，走到能晒到光的地方，5 分钟就够。",
    "s.end.selfcare.tips": "可以跟我做：慢慢呼吸几轮，或者出去走一小圈；也可以去树洞写写心里话。",
    "s.end.selfcare.title": "谢谢你愿意说出来。",
    "s.explore.hint": "可以多选，选最贴近的几个就好。",
    "s.explore.option.exam": "考试",
    "s.explore.option.family": "家庭",
    "s.explore.option.future": "对未来的担心",
    "s.explore.option.other": "其他",
    "s.explore.option.relationship": "同学关系",
    "s.explore.option.sleep": "睡眠",
    "s.explore.option.study": "学习",
    "s.explore.subtitle": "最近是什么让你有这种感觉？",
    "s.explore.title": "情绪探索",
    "s.feedback.category.campus_env": "校园环境",
    "s.feedback.category.canteen": "食堂",
    "s.feedback.category.dormitory": "宿舍",
    "s.feedback.category.facility": "教室 / 设施",
    "s.feedback.category.other": "其他",
    "s.feedback.category.schedule": "作息 / 时间安排",
    "s.feedback.category.title": "这件事更像哪一类？",
    "s.feedback.mine.categoryPrefix": "分类：",
    "s.feedback.mine.empty": "你还没有提交过学校的反馈。想到了随时可以写。",
    "s.feedback.mine.placeholderToken": "已经隐去的部分会显示成这样：[已隐去]",
    "s.feedback.mine.sanitizedLabel": "实际送出去的文本（已隐去能认出人的部分）",
    "s.feedback.mine.sanitizedNote": "姓名、班级、宿舍号这类信息会被隐去，你写的话本身不会被改写。",
    "s.feedback.mine.status.inProgress": "正在看",
    "s.feedback.mine.status.pending": "已收到",
    "s.feedback.mine.status.resolved": "已经处理",
    "s.feedback.mine.status.void": "已关闭",
    "s.feedback.mine.title": "我提交过的反馈",
    "s.feedback.scope.label": "影响范围（选填）",
    "s.feedback.scope.placeholder": "比如：整层宿舍楼、我们班、只有我一个人遇到。",
    "s.feedback.submit": "提交",
    "s.feedback.submitted": "已经提交上去了。相关部门会看到这段内容。",
    "s.feedback.suggestion.label": "你的建议（选填）",
    "s.feedback.suggestion.placeholder": "比如：希望延长热水供应时间。",
    "s.help.body": "选「请求帮助」，你这次写下的内容会带给心理老师，老师会尽快看到。选「不用帮助」，内容就留在你这里，一样会被好好保存。",
    "s.help.hint": "怎么选都可以，两种选择都不会让你被追问。",
    "s.help.option.no": "不用帮助",
    "s.help.option.no.note": "只有你自己能看到。如果之后想让老师知道，也可以随时改主意。",
    "s.help.option.request": "请求心理老师帮助",
    "s.help.option.request.note": "老师会看到你这次写的内容。",
    "s.help.selected.no": "已选择：内容只留在你这里。",
    "s.help.selected.request": "已选择：老师可以看到你这次写的内容。",
    "s.help.title": "要不要让心理老师陪你一起看看？",
    "s.notice.action.agree": "我知道了，开始",
    "s.notice.action.exit": "先不填",
    "s.notice.item1": "你填的内容只用于学校里的心理支持，不做别的用途。",
    "s.notice.item2": "内容默认只有你自己能看到。只有你选了「请求心理老师帮助」，老师才会看到这次的内容。",
    "s.notice.item3": "树洞里的内容永远是私密的，老师看不到，也不会进入任何统计。",
    "s.notice.item4": "如果和学校的食堂、宿舍、设施有关，你可以写在专门的那一栏，我们会以匿名方式转给学校相关部门。",
    "s.notice.item5": "你可以随时决定不再填写。如果填完之后改主意了，也可以在「我的档案」里点「不让老师看了」，让这一条重新变成只有你自己能看到。",
    "s.notice.item6": "撤回之后不能再改回\"老师可以看到\"，想再让老师知道，重新填一次就可以。",
    "s.notice.title": "开始之前，想先和你说清楚",
    "s.q1.hint.optional": "这一题选了就好，不用想太久。",
    "s.q1.option.down": "沮丧",
    "s.q1.option.down.emoji": "😣",
    "s.q1.option.happy": "高兴",
    "s.q1.option.happy.emoji": "☀️",
    "s.q1.option.plain": "平淡",
    "s.q1.option.plain.emoji": "☁️",
    "s.q1.subtitle": "没有对错，按第一感觉选就好。",
    "s.q1.title": "今天的你，感觉怎么样？",
    "s.q2.option.family": "家庭矛盾",
    "s.q2.option.relationship": "人际关系",
    "s.q2.option.study": "学业",
    "s.q2.subtitle": "选一个最接近的就好，之后还可以再补充。",
    "s.q2.title": "你是因为什么原因？",
    "s.q25.disclosure.anonymous": "你写的内容会以匿名方式转给学校相关部门（不包含你的姓名和班级）。",
    "s.q25.disclosure.extra": "写的时候不用写自己的名字，也不用写同学的。",
    "s.q25.disclosure.materialOnly": "这段内容只会转给学校相关部门，不会转给心理老师。",
    "s.q25.followup.action.back": "上一步",
    "s.q25.followup.action.submit": "提交给学校相关部门",
    "s.q25.followup.error.empty": "选了这个选项，就多写一句吧，一句话也可以。",
    "s.q25.followup.placeholder": "例如：宿舍晚上十一点后就没有热水了；食堂午餐排队太久来不及吃……",
    "s.q25.followup.subtitle": "写清楚「哪里」和「什么问题」就好，不用写自己的名字，也不用写同学的。",
    "s.q25.followup.title": "方便说一下具体是什么情况吗？",
    "s.q25.option.no": "没关系",
    "s.q25.option.skip": "不确定 / 先跳过",
    "s.q25.option.yes": "有关系",
    "s.q25.sensitive.alt": "如果现在很难受，可以打 12356，随时有人接。",
    "s.q25.sensitive.body": "你写的这些，可能更需要被一位心理老师认真看一看。我们不会把它转给学校相关部门，而是交给心理老师。",
    "s.q25.sensitive.next": "继续",
    "s.q25.sensitive.notice": "这段内容会由心理老师来看。",
    "s.q25.subtitle": "比如食堂、宿舍、教室设施、校园环境这些。没有的话，直接跳过就好。",
    "s.q25.title": "这次的低落，和学校的物质条件有关系吗？",
    "s.q3.counter.hidden": "（不显示字数上限、不显示\"还剩 X 字\"、不做倒计时）",
    "s.q3.error.empty": "写一点点也可以，哪怕只有一句话。",
    "s.q3.guide.1": "可以是一件小事",
    "s.q3.guide.2": "想到什么就写什么",
    "s.q3.guide.3": "如果觉得乱也没关系",
    "s.q3.placeholder": "慢慢写，写给自己看也可以。",
    "s.q3.subtitle": "想到多少写多少，不限字数。你写下的内容默认只有你自己能看到。",
    "s.q3.title": "请你详细阐述一下原因",
    "s.revoke.after.helpEntry": "也可以直接找心理老师当面聊，不需要通过这份问卷。",
    "s.revoke.after.note": "这一条已经不让老师看了。内容还留在这里，你随时可以回来看。",
    "s.revoke.after.relink": "想重新让老师知道，重新填一次问卷、在最后一步选「请求心理老师帮助」就可以。",
    "s.revoke.badge.private": "只有你自己能看到",
    "s.revoke.badge.revoked": "只有你自己能看到",
    "s.revoke.badge.shared": "老师可以看到",
    "s.revoke.confirm.action.cancel": "再想想",
    "s.revoke.confirm.action.ok": "好，不让老师看了",
    "s.revoke.confirm.body": "老师那边就不会再看到这段内容了。",
    "s.revoke.confirm.irreversible": "这一下点了就不能改回来。如果你之后又想告诉老师，需要重新填一次问卷。",
    "s.revoke.confirm.keepNote": "你写下的内容不会消失，只是重新变成只有你自己能看到。",
    "s.revoke.confirm.title": "不让老师看这一条了？",
    "s.revoke.entry.action": "不让老师看了",
    "s.revoke.entry.action.revoked": "已经不让老师看了",
    "s.revoke.entry.disabledTip": "这一条本来只有你自己能看到。",
    "s.revoke.entry.hint": "点了之后，老师就看不到这一条了。",
    "s.revoke.error.1002": "这条记录不在你的档案里，所以没法操作。",
    "s.revoke.error.2001.notShared": "这一条本来就只有你自己能看到，不用再改。",
    "s.revoke.error.2001.restore": "这里只能改成不让老师看，不能改回去。想再让老师知道，重新填一次问卷就好。",
    "s.revoke.error.2002": "没有找到这一条，可能已经不在档案里了。",
    "s.revoke.error.network": "网络好像有点慢，等会儿再试就好。",
    "s.revoke.toast.alreadyRevoked": "这一条已经是不让老师看的状态了。",
    "s.revoke.toast.done": "好，老师那边看不到这一条了。",
    "s.revoke.toast.doneNote": "内容还在这里，你可以随时回来看。",
    "s.revoke.toast.failed": "刚才没改成，再试一次就好。",
    "s.revoke.toast.notFound": "没有找到这一条，可能已经不在档案里了。",
    "s.revoke.toast.notShared": "这一条本来就只有你自己能看到。",
    "s.treehole.compose.action.cancel": "取消",
    "s.treehole.compose.action.save": "保存",
    "s.treehole.compose.error.empty": "写一点点也可以，哪怕只有一句话。",
    "s.treehole.compose.placeholder": "今天想写点什么……",
    "s.treehole.compose.privacyLabel": "只有你自己能看到",
    "s.treehole.compose.privacyNote": "这段话不会出现在任何别的地方，也不会被算进任何统计里。",
    "s.treehole.compose.title": "今天想写点什么",
    "s.treehole.entry.subtitle": "有些话说出来，就会轻一点。",
    "s.treehole.entry.title": "树洞 · 说给谁听都可以",
    "s.treehole.list.empty": "这里还空着。想写的时候，随时都可以来。",
    "s.treehole.list.item.privacyBadge": "仅自己可见",
    "s.treehole.list.new": "写一句",
    "s.treehole.list.noReadReceipt": "这里不会显示谁看过，写起来会自在一点。",
    "s.treehole.list.privacyNote": "这里只有你自己能看到，别人不会知道你写没写。",
    "s.treehole.list.title": "我的树洞",
    "s.treehole.moodtag.label": "给今天加个标记（选填）",
    "s.treehole.moodtag.option.down": "沮丧",
    "s.treehole.moodtag.option.happy": "高兴",
    "s.treehole.moodtag.option.none": "不加",
    "s.treehole.moodtag.option.plain": "平淡",
    "s.treehole.save.done": "已经存好了。",
    "s.treehole.save.donePrivate": "已经存好了，只有你自己能看到。",
    "s.treehole.tab.title": "树洞",
    "t.ack.dialog.accept.body": "受理后，这条求助会从\"待回应\"移到\"已受理\"，其他老师也能看到你已经在跟进了。",
    "t.ack.dialog.accept.confirm": "受理",
    "t.ack.dialog.accept.noteLabel": "备注（选填）",
    "t.ack.dialog.accept.notePlaceholder": "比如：今天下午课间找她聊了十分钟。",
    "t.ack.dialog.accept.title": "受理这条求助？",
    "t.ack.dialog.cancel": "取消",
    "t.ack.dialog.done.body": "确认这次陪伴告一段落。之后学生再提交新的求助，会重新出现在名单里。",
    "t.ack.dialog.done.confirm": "标记为已处理",
    "t.ack.dialog.done.noteLabel": "备注（选填）",
    "t.ack.dialog.done.notePlaceholder": "比如：已经聊过，约了下周再聊一次。",
    "t.ack.dialog.done.title": "标记为已处理？",
    "t.ack.toast.accept": "已受理。辛苦你了。",
    "t.ack.toast.done": "已经记下了。",
    "t.ack.toast.failed": "刚才没记上，再试一次就好。",
    "t.detail.alert.body": "近 {window_n} 次记录中低落 {count} 次，因此在名单里排得靠前。这是排序参考，不是对学生的判断。",
    "t.detail.alert.label": "排序提示",
    "t.detail.close": "关闭",
    "t.detail.count.label": "今日填写次数",
    "t.detail.count.value": "{count} 次",
    "t.detail.date": "{date}",
    "t.detail.mood.down": "沮丧",
    "t.detail.mood.happy": "高兴",
    "t.detail.mood.label": "今天的心情",
    "t.detail.mood.none": "今天还没有填写",
    "t.detail.mood.plain": "平淡",
    "t.detail.pending.label": "待处理求助",
    "t.detail.pending.no": "没有待处理的求助",
    "t.detail.pending.yes": "有 {count} 条还没有受理",
    "t.detail.reason.family": "家庭矛盾",
    "t.detail.reason.label": "学生选择的原因",
    "t.detail.reason.relationship": "人际关系",
    "t.detail.reason.study": "学业",
    "t.detail.revoked.body": "内容不再显示在这里。学生改主意是允许的，也不需要向你解释；名单上的排序不受影响。",
    "t.detail.revoked.title": "这一条学生已经改回只有他自己能看到了",
    "t.detail.shared.action.ticket": "受理这条求助",
    "t.detail.shared.action.ticketDone": "这条求助已经处理完了",
    "t.detail.shared.disclaimer": "这些内容来自学生自己填写的问卷，只是他当时的一个片段，不能替代你和他当面的了解。",
    "t.detail.shared.item.cause": "当时原因：{cause}",
    "t.detail.shared.item.detailLabel": "学生写的话",
    "t.detail.shared.item.mood": "当时心情：{mood}",
    "t.detail.shared.item.time": "填写时间：{time}",
    "t.detail.shared.privacyNote": "这些是学生选择「请求帮助」后带过来的内容。",
    "t.detail.shared.title": "学生愿意让你看到的内容",
    "t.detail.title": "当日状态",
    "t.detail.unshared.body": "这次学生把内容留给了自己，这本身也是一种照顾自己的方式。你仍然可以像平常一样，在课间或课后和他聊两句，不用提这份问卷。",
    "t.detail.unshared.noInference": "（此处不展示任何由计数推断出的内容。）",
    "t.detail.unshared.reminder": "名单上的排序还在，说明我们早知道要早点留意；但具体发生了什么，等他愿意说的时候再听。",
    "t.detail.unshared.revokedNote": "学生也可以在填完之后改主意，让某一条重新变成只有他自己能看到。出现这种情况时，说明他正在按自己的节奏来，不需要追问原因。",
    "t.detail.unshared.title": "该生选择暂不分享，可通过线下方式关心",
    "t.login.action.submit": "进入",
    "t.login.demo.action": "离线演示（只看本地预约库）",
    "t.login.demo.note": "服务端没起时，可以先只看本机的预约库。",
    "t.login.error.401": "工号或口令对不上，再试一次就好。",
    "t.login.error.empty": "工号和口令都填一下就好。",
    "t.login.error.network": "暂时连不上服务，稍后再试就好。",
    "t.login.field.id": "工号",
    "t.login.field.password": "口令",
    "t.login.footer": "演示环境 · 请勿填入真实学生信息",
    "t.login.placeholder.id": "请输入工号",
    "t.login.placeholder.password": "请输入口令",
    "t.login.subtitle": "今天也谢谢你愿意多看一眼这些孩子。",
    "t.login.title": "欢迎回来",
    "t.login.window.title": "MindCare · 心理老师端",
    "t.schedule.action.block": "设为不可预约",
    "t.schedule.action.blocked": "已设成不可预约，学生那边已经看不到了。",
    "t.schedule.action.failed": "刚才没改上，再点一次试试。",
    "t.schedule.action.refresh": "刷新",
    "t.schedule.action.unblock": "恢复可预约",
    "t.schedule.action.unblocked": "已经恢复，学生又能约这一节了。",
    "t.schedule.detail.class": "班级",
    "t.schedule.detail.count": "共 {count} 人",
    "t.schedule.detail.empty": "这个时间还没有人预约。",
    "t.schedule.detail.noShare": "这位同学只给了班级、学号和预约时间。",
    "t.schedule.detail.share.q.no": "这次的测评内容 TA 没有分享",
    "t.schedule.detail.share.q.yes": "愿意让你看 TA 这次的测评内容",
    "t.schedule.detail.share.t.no": "树洞记录 TA 没有分享",
    "t.schedule.detail.share.t.yes": "愿意让你看 TA 的树洞记录",
    "t.schedule.detail.sid": "学号",
    "t.schedule.detail.student": "姓名",
    "t.schedule.detail.time": "时间",
    "t.schedule.detail.title": "这个时间的预约",
    "t.schedule.hint.toggle": "设成不可预约后，学生端会立刻显示成红框，点不了。",
    "t.schedule.selected.none": "点一个小方块，看看这段时间谁约了。",
    "t.schedule.subtitle": "和学生看到的是同一张表。点一个小方块，就能把它设成不可预约，学生那边马上会看到。",
    "t.schedule.title": "预约时间表",
    "t.tab.schedule": "预约时间",
    "t.triage.action.refresh": "刷新",
    "t.triage.action.refreshing": "正在刷新…",
    "t.triage.chip.history": "病史",
    "t.triage.chip.none": "暂无标记",
    "t.triage.chip.pendingHelp": "求助待处理",
    "t.triage.chip.recentDown": "近{n}次低落×{count}",
    "t.triage.chip.tooltip.history": "入学档案里有既往病史记录，来自学校既有档案，不是系统算出来的。",
    "t.triage.chip.tooltip.pendingHelp": "这位学生点了「请求心理老师帮助」，还没有人受理。",
    "t.triage.chip.tooltip.recentDown": "最近 {window_n} 次问卷里，有 {count} 次选了「沮丧」。",
    "t.triage.col.daysSince": "距今天数",
    "t.triage.col.flags": "标记",
    "t.triage.col.lastActive": "最后活跃",
    "t.triage.col.priority": "关怀顺序",
    "t.triage.col.student": "姓名 / 班级",
    "t.triage.days.n": "{n} 天前",
    "t.triage.days.today": "今天",
    "t.triage.days.unknown": "还没有记录",
    "t.triage.params.note": "排序依据：心理老师设置的回看窗口与阈值（当前：近 {window_n} 次记录中出现 {threshold_k} 次低落）。",
    "t.triage.priority.1": "需要优先关心",
    "t.triage.priority.1.note": "这类学生有既往病史标记，且最近几次记录里低落出现得比较多，建议早一点约一次聊天。",
    "t.triage.priority.2": "有待回应",
    "t.triage.priority.2.note": "这位学生选择了请求帮助，还在等一个回应。",
    "t.triage.priority.3": "常规关注",
    "t.triage.priority.3.note": "最近有记录，可以保持留意。",
    "t.triage.priority.legend": "排序只是提醒你先看谁，不代表学生有什么问题。",
    "t.triage.subtitle": "按关怀顺序排好的名单，点开可以看到学生愿意让你看到的内容。",
    "t.triage.sync.countdown": "下次刷新还有 {seconds} 秒",
    "t.triage.sync.last": "最后同步：{time}",
    "t.triage.title": "分诊台",
    "t.window.title": "MindCare 教师端",
}

__all__ = ["TEXT"]
